resources:
#  - db-migrate.yaml
  - deployment-idp.yaml
  - deployment-jobrunner.yaml
  - canary.yml
  - autoscaler.yml
  - github.com/weaveworks/flagger//kustomize/tester
# secretGenerator:
# - name: application.yml
#   files:
#     - ../../../identity-idp/config/application.yml.default
images:
- name: gsatspencer/identity-idp
  newTag: 1.1.6
