apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp
  labels:
    app: idp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idp
  template:
    metadata:
      labels:
        app: idp
    spec:
      containers:
      - name: idp
        image: timspencer/idp:1.0.3
        env:
        - name: RAILS_ENV
          value: production
        - name: NEW_RELIC_AGENT_ENABLED
          value: false
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: appconfig
          mountPath: "/upaya/config/application.yml"
          readOnly: true
        - name: agencies
          mountPath: "/upaya/config/agencies.yml"
          readOnly: true
        - name: certs
          mountPath: "/upaya/certs"
          readOnly: true
        - name: keys
          mountPath: "/upaya/keys"
          readOnly: true
        - name: pwnedpasswords
          mountPath: "/upaya/pwned_passwords/pwned_passwords.txt"
          readOnly: true
        - name: serviceproviders
          mountPath: "/upaya/config/service_providers.yml"
          readOnly: true
      volumes:
      - name: appconfig
        secret:
          secretName: application.yml
      - name: agencies
        secret:
          secretName: agencies.yml
      - name: certs
        secret:
          secretName: certs
      - name: keys
        secret:
          secretName: keys
      - name: pwnedpasswords
        secret:
          secretName: pwnedpasswords.txt
      - name: serviceproviders
        secret:
          secretName: serviceproviders.yml
