apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp
  labels:
    app: idp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idp
  template:
    metadata:
      labels:
        app: idp
    spec:
      containers:
      - name: idp
        image: timspencer/idp:1.0.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: application.yml
          mountPath: "/upaya/app/config/application.yml"
          readOnly: true
      volumes:
      - name: application.yml
        secret:
          secretName: application.yml
