apiVersion: v1
kind: Service
metadata:
  name: idp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
spec:
  selector:
    app: idp
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer
